filter:
  excluded_paths:
    - tests/*

build:
  dependencies:
    override:
      - true
  nodes:
    analysis:
      tests:
        override:
          - phpunit --configuration phpunit.xml --exclude-group uses_real_com
          - php-scrutinizer-run