filter:
  excluded_paths:
    - tests/*

checks:
  php:
    excluded_dependencies:
      - ext-com_dotnet

build:
  nodes:
    analysis:
      tests:
        override:
          - php ./vendor/bin/phpunit --configuration phpunit.xml --exlude-group uses_real_com
          - php-scrutinizer-run