filter:
  excluded_paths:
    - tests/*

build:
  dependencies:
    override:
      -
        command: composer install --ignore-platform-reqs --no-interaction --prefer-dist --no-suggest
  nodes:
    analysis:
      tests:
        override:
          - command: vendor/bin/phpunit --configuration phpunit.xml --exclude-group uses_real_com
          - php-scrutinizer-run