sudo: required
dist: xenial
language: php
dotnet: 2.2

php:
  - '7.1'
  - '7.2'
  - '7.3'

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script: ./vendor/bin/phpunit

branches:
  only:
    - master
