matrix:
  fast_finish: true
  include:
    - os: windows
      language: sh
      env:
        - PHP_VERSION=7.1.25
        - PHP_DIR=php71
        - XDEBUG=https://xdebug.org/files/php_xdebug-2.8.0beta1-7.1-vc14-nts-x86_64.dll
    - os: windows
      language: sh
      env:
        - PHP_VERSION=7.2.20
        - PHP_DIR=php72
        - XDEBUG=https://xdebug.org/files/php_xdebug-2.8.0beta1-7.2-vc15-nts-x86_64.dll
    - os: windows
      language: sh
      env:
        - PHP_VERSION=7.3.8
        - PHP_DIR=php73
        - XDEBUG=https://xdebug.org/files/php_xdebug-2.8.0beta1-7.3-vc15-nts-x86_64.dll

cache:
  directories:
    # Common cache directories
    - vendor
    - $HOME/AppData/Local/Temp/chocolatey

    # Cache PHP and Composer install
    - /c/tools/$PHP_DIR
    - /c/ProgramData/ComposerSetup/bin

before_install:
  # Install PHP, Configure INI, and setup PATH
  - if [[ ! -f "/c/tools/$PHP_DIR/php.ini" ]]; then choco install php --version $PHP_VERSION -y; ./bin/ci/setup_php.sh;  fi
  - export PATH=/c/tools/$PHP_DIR:$PATH;

  # Download CA Bundle
  - travis_retry wget https://curl.haxx.se/ca/cacert.pem -O /c/tools/cacert.pem -q;

  # Install Composer and modify PATH
  - if [[ ! -f "/c/ProgramData/ComposerSetup/bin/composer.bat" ]]; then choco install composer -i;  fi
  - export PATH=/c/ProgramData/ComposerSetup/bin:$PATH;

  # Make sure composer is up-to-date
  - travis_retry composer self-update

install:
  - travis_retry composer update --no-interaction --prefer-dist --no-suggest

before_script:
  # Download appropriate XDebug and modify configuration
  - travis_retry wget $XDEBUG -O /c/tools/$PHP_DIR/ext/xdebug.dll -q;
  - ./bin/ci/start_xdebug.sh;

script: ./vendor/bin/phpunit --coverage-clover=/c/tools/$PHP_DIR/coverage.clover

# Remove XDebug from INI before cache
before_cache: ./bin/ci/stop_xdebug.sh;

after_script:
  - travis_retry wget https://github.com/scrutinizer-ci/ocular/releases/download/1.5.2/ocular.phar -q;
  - php ocular.phar code-coverage:upload --format=php-clover /c/tools/$PHP_DIR/coverage.clover 2>&1
