matrix:
  fast_finish: true
  include:
    - os: windows
      language: sh
      env:
        - PHP_VERSION=7.2.13
        - PHP_DIR=php72

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - choco install php --version $PHP_VERSION -y;
  - export PATH=/c/tools/$PHP_DIR:$PATH;
  - echo 'extension_dir="ext"' >> /c/tools/$PHP_DIR/php.ini
  - echo "extension=php_openssl.dll" >> /c/tools/$PHP_DIR/php.ini;
  - echo "extension=php_mbstring.dll" >> /c/tools/$PHP_DIR/php.ini
  - echo "extension=php_pdo_mysql.dll" >> /c/tools/$PHP_DIR/php.ini
  - echo "extension=php_pdo_sqlite.dll" >> /c/tools/$PHP_DIR/php.ini
  - echo "extension=php_fileinfo.dll" >> /c/tools/$PHP_DIR/php.ini
  - echo "extension=php_gd2.dll" >> /c/tools/$PHP_DIR/php.ini
  - echo "extension=php_ftp.dll" >> /c/tools/$PHP_DIR/php.ini
  - echo "extension=php_com_dotnet.dll" >> /c/tools/$PHP_DIR/php.ini
  - echo "memory_limit=256M" >> /c/tools/$PHP_DIR/php.ini
  - wget https://raw.githubusercontent.com/composer/getcomposer.org/d3e09029468023aa4e9dcd165e9b6f43df0a9999/web/installer -O - -q | php --
  - travis_retry php composer.phar self-update

install:
  - travis_retry php composer.phar update --no-interaction --prefer-stable --prefer-dist --no-suggest

script: ./vendor/bin/phpunit --coverage-clover=coverage.clover

#after_script:
#  - wget https://scrutinizer-ci.com/ocular.phar
#  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover 2>&1
