<?php

namespace PhpWinTools\WmiScripting\MappingStrings;

class OSType extends Mappings
{
    const UNKNOWN           = 0;
    const OTHER             = 1;
    const MACOS             = 2;
    const ATTUNIX           = 3;
    const DGUX              = 4;
    const DECNT             = 5;
    const DIGITAL_UNIX      = 6;
    const OPENVMS           = 7;
    const HPUX              = 8;
    const AIX               = 9;
    const MVS               = 10;
    const OS400             = 11;
    const OS_2              = 12;
    const JAVAVM            = 13;
    const MSDOS             = 14;
    const WIN3X             = 15;
    const WIN95             = 16;
    const WIN98             = 17;
    const WINNT             = 18;
    const WINCE             = 19;
    const NCR3000           = 20;
    const NETWARE           = 21;
    const OSF               = 22;
    const DC_OS             = 23;
    const RELIANT_UNIX      = 24;
    const SCO_UNIXWARE      = 25;
    const SCO_OPENSERVER    = 26;
    const SEQUENT           = 27;
    const IRIX              = 28;
    const SOLARIS           = 29;
    const SUNOS             = 30;
    const U6000             = 31;
    const ASERIES           = 32;
    const TANDEMNSK         = 33;
    const TANDEMNT          = 34;
    const BS2000            = 35;
    const LINUX             = 36;
    const LYNX              = 37;
    const XENIX             = 38;
    const VM_ESA            = 39;
    const INTERACTIVE_UNIX  = 40;
    const BSDUNIX           = 41;
    const FREEBSD           = 42;
    const NETBSD            = 43;
    const GNU_HURD          = 44;
    const OS9               = 45;
    const MACH_KERNEL       = 46;
    const INFERNO           = 47;
    const QNX               = 48;
    const EPOC              = 49;
    const IXWORKS           = 50;
    const VXWORKS           = 51;
    const MINT              = 52;
    const BEOS              = 53;
    const HP_MPE            = 54;
    const NEXTSTEP          = 55;
    const PALMPILOT         = 56;
    const RHAPSODY          = 57;
    const WINDOWS_2000      = 58;
    const DEDICATED         = 59;
    const OS_390            = 60;
    const VSE               = 61;
    const TPF               = 62;

    const STRING_ARRAY = [
        self::UNKNOWN           => 'UNKNOWN',
        self::OTHER             => 'OTHER',
        self::MACOS             => 'MACOS',
        self::ATTUNIX           => 'ATTUNIX',
        self::DGUX              => 'DGUX',
        self::DECNT             => 'DECNT',
        self::DIGITAL_UNIX      => 'DIGITAL_UNIX',
        self::OPENVMS           => 'OPENVMS',
        self::HPUX              => 'HPUX',
        self::AIX               => 'AIX',
        self::MVS               => 'MVS',
        self::OS400             => 'OS400',
        self::OS_2              => 'OS_2',
        self::JAVAVM            => 'JAVAVM',
        self::MSDOS             => 'MSDOS',
        self::WIN3X             => 'WIN3X',
        self::WIN95             => 'WIN95',
        self::WIN98             => 'WIN98',
        self::WINNT             => 'WINNT',
        self::WINCE             => 'WINCE',
        self::NCR3000           => 'NCR3000',
        self::NETWARE           => 'NETWARE',
        self::OSF               => 'OSF',
        self::DC_OS             => 'DC_OS',
        self::RELIANT_UNIX      => 'RELIANT_UNIX',
        self::SCO_UNIXWARE      => 'SCO_UNIXWARE',
        self::SCO_OPENSERVER    => 'SCO_OPENSERVER',
        self::SEQUENT           => 'SEQUENT',
        self::IRIX              => 'IRIX',
        self::SOLARIS           => 'SOLARIS',
        self::SUNOS             => 'SUNOS',
        self::U6000             => 'U6000',
        self::ASERIES           => 'ASERIES',
        self::TANDEMNSK         => 'TANDEMNSK',
        self::TANDEMNT          => 'TANDEMNT',
        self::BS2000            => 'BS2000',
        self::LINUX             => 'LINUX',
        self::LYNX              => 'LYNX',
        self::XENIX             => 'XENIX',
        self::VM_ESA            => 'VM_ESA',
        self::INTERACTIVE_UNIX  => 'INTERACTIVE_UNIX=>',
        self::BSDUNIX           => 'BSDUNIX',
        self::FREEBSD           => 'FREEBSD',
        self::NETBSD            => 'NETBSD',
        self::GNU_HURD          => 'GNU_HURD',
        self::OS9               => 'OS9',
        self::MACH_KERNEL       => 'MACH_KERNEL',
        self::INFERNO           => 'INFERNO',
        self::QNX               => 'QNX',
        self::EPOC              => 'EPOC',
        self::IXWORKS           => 'IXWORKS',
        self::VXWORKS           => 'VXWORKS',
        self::MINT              => 'MINT',
        self::BEOS              => 'BEOS',
        self::HP_MPE            => 'HP_MPE',
        self::NEXTSTEP          => 'NEXTSTEP',
        self::PALMPILOT         => 'PALMPILOT',
        self::RHAPSODY          => 'RHAPSODY',
        self::WINDOWS_2000      => 'WINDOWS_2000',
        self::DEDICATED         => 'DEDICATED',
        self::OS_390            => 'OS_390',
        self::VSE               => 'VSE',
        self::TPF               => 'TPF',
    ];
}
