<?php

namespace Tests\WmiScripting\Support\Bus;

use Closure;
use PhpWinTools\WmiScripting\Configuration\Config;
use PhpWinTools\WmiScripting\Support\Bus\CommandBus;
use PhpWinTools\WmiScripting\Support\Bus\Commands\Command;
use PhpWinTools\WmiScripting\Support\Bus\CoreBus;
use PhpWinTools\WmiScripting\Support\Bus\Middleware\MiddlewareProcessor;
use PhpWinTools\WmiScripting\Support\Bus\Middleware\PreCommandMiddleware;
use Tests\TestCase;

class CoreBusTest extends TestCase
{
    /** @test */
    public function it_can_instantiate()
    {
        $config = new Config();
        $bus = new CoreBus();

        $this->assertInstanceOf(CoreBus::class, $bus);
        $this->assertSame($config, $bus->getConfig());
        $this->assertSame(CoreBus::instance(), $bus);
    }

    /** @test */
    public function it_runs_middleware_before_command()
    {
        $command = new class extends Command {};

        $first_middleware = new class extends PreCommandMiddleware {
            public $name = 'first';
            public function handle(Command $command, Closure $next)
            {
                dump($this->name);
                return parent::handle($command, $next); // TODO: Change the autogenerated stub
            }
        };
        $second_middleware = new class extends PreCommandMiddleware {
            public $name = 'second';
            public function handle(Command $command, Closure $next)
            {
                dump($this->name);
                return parent::handle($command, $next); // TODO: Change the autogenerated stub
            }
        };

        $bus = CoreBus::instance()
            ->registerMiddleware(get_class($first_middleware), get_class($command))
            ->registerMiddleware(get_class($second_middleware), get_class($command));
        dump($bus->handle($command));
        dd(MiddlewareProcessor::instance()->fired());
    }
}
